name: Test branch in docker
on: [ push ]
jobs:
  test-in-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Prepare docker
        uses: docker/setup-buildx-action@v1
      - run: ${{ github.workspace }}/gradlew build
      - run: ${{ github.workspace }}/gradlew docker
      - run: ${{ github.workspace }}/gradlew dockerRun
      - run: ${{ github.workspace }}/gradlew integrationTest
      - run: echo "done"
